-- OUT에는 있고 IN에는 없는
SELECT
    O.ANIMAL_ID,
    O.NAME
FROM ANIMAL_INS I
RIGHT JOIN ANIMAL_OUTS O 
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL AND O.ANIMAL_ID IS NOT NULL
ORDER BY ANIMAL_ID ASC, NAME ASC