-- 코드를 작성해주세요
SELECT 
    ROUTE,
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC


/* ORDER BY는 이제 더 이상 TOTAL_DISTANCE로 하면 안된다.
CONCAT으로 숫자가 아니게 되버렸음.
해서 위와 같이 작성한다.
*/