
WITH RECURSIVE GEN AS(
SELECT ID
    , PARENT_ID
    , 1 AS GENERATION
FROM ECOLI_DATA G
WHERE PARENT_ID IS NULL

UNION ALL

SELECT D.ID
    , D.PARENT_ID
    , G.GENERATION +1
FROM ECOLI_DATA D
JOIN GEN G 
    ON D.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT
    , A.GENERATION
FROM GEN A
LEFT JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID
WHERE B.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION

