SELECT P.PRODUCT_ID
    , P.PRODUCT_NAME
    , SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
INNER JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE 1=1
AND PRODUCE_DATE >= '2022-05-01'
AND PRODUCE_DATE < '2022-06-01'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID 