-- 완료된 중고 거래의 총금액이 70만원 이상인 사람의 회원 ID, 닉네임, 총거래금액 조회
/*
SELECT
    USER_ID,
    NICKNAME,
    SUM(PRICE)
    AS TOTAL_SALES
FROM 
    USED_GOODS_BOARD, USED_GOODS_USER
WHERE WRITER_ID = USER_ID AND STATUS = 'DONE'
GROUP BY USER_ID 
HAVING SUM(PRICE) >= 700000 -- 그룹화 이후라 TOTAL_SALES도 가능하다
ORDER BY TOTAL_SALES
*/
-- join
SELECT 
    U.USER_ID, 
    U.NICKNAME, 
    SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
LEFT JOIN 
    USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID, B.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;



-- https://kkw-da.tistory.com/entry/SQL-%EC%A1%B0%EA%B1%B4%EC%97%90-%EB%A7%9E%EB%8A%94-%EC%82%AC%EC%9A%A9%EC%9E%90%EC%99%80-%EC%B4%9D-%EA%B1%B0%EB%9E%98%EA%B8%88%EC%95%A1-%EC%A1%B0%ED%9A%8C%ED%95%98%EA%B8%B0%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4MySQLLevel-3