-- 코드를 작성해주세요
WITH EMP_SCORE AS (
    SELECT 
        EMP_NO,
    CASE WHEN AVG(SCORE) >= 96  THEN 'S'
        WHEN AVG(SCORE) >= 90  THEN 'A'
        WHEN AVG(SCORE) >= 80  THEN 'B'
        ELSE 'C' END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO)

SELECT 
    H.EMP_NO,
    H.EMP_NAME,
    E.GRADE,
    CASE WHEN E.GRADE = 'S' THEN SAL * 20/100
    WHEN E.GRADE = 'A' THEN SAL * 15/100
    WHEN E.GRADE = 'B' THEN SAL * 10/100
    ELSE 0 END AS BONUS
FROM HR_EMPLOYEES H
JOIN EMP_SCORE E
ON H.EMP_NO = E.EMP_NO
ORDER BY H.EMP_NO
/*

-- WITH절 만들기
SELECT 
       EMP_NO,
       SCORE
FROM HR_GRADE   


-- 점수에 따른 GRADE 테이블 만들기
SELECT 
    EMP_NO,
    CASE WHEN SCORE >= 96  THEN 'S'
    WHEN SCORE >= 90  THEN 'A'
    WHEN SCORE >= 80  THEN 'B'
    ELSE 'C' END AS GRADE
FROM HR_GRADE
    
-- 그룹으로 묶고 그룹별 평균으로 점수를 바꿔서 조건 걸기
SELECT 
    EMP_NO,
    CASE WHEN AVG(SCORE) >= 96  THEN 'S'
    WHEN AVG(SCORE) >= 90  THEN 'A'
    WHEN AVG(SCORE) >= 80  THEN 'B'
    ELSE 'C' END AS GRADE
FROM HR_GRADE
GROUP BY EMP_NO;


-- WITH절로 묶기 이때 가상 테이블인 WITH 절 이외 SELECT 절을 안해주면 오류남
WITH EMP_SCORE AS (
    SELECT 
        EMP_NO,
    CASE WHEN AVG(SCORE) >= 96  THEN 'S'
        WHEN AVG(SCORE) >= 90  THEN 'A'
        WHEN AVG(SCORE) >= 80  THEN 'B'
        ELSE 'C' END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO)

SELECT 
    EMP_NO,
    GRADE
FROM EMP_SCORE


-- HR_EMPLOYEES와 가상 테이블 EMP_SCORE JOIN하기.
-- 아직 
WITH EMP_SCORE AS (
    SELECT 
        EMP_NO,
    CASE WHEN AVG(SCORE) >= 96  THEN 'S'
        WHEN AVG(SCORE) >= 90  THEN 'A'
        WHEN AVG(SCORE) >= 80  THEN 'B'
        ELSE 'C' END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO)

SELECT 
    H.EMP_NO,
    H.EMP_NAME,
    E.GRADE,
    H.SAL AS BONUS
FROM HR_EMPLOYEES H
JOIN EMP_SCORE E
ON H.EMP_NO = E.EMP_NO


-- GRADE별 BONUS 컬럼 만들기 
WITH EMP_SCORE AS (
    SELECT 
        EMP_NO,
    CASE WHEN AVG(SCORE) >= 96  THEN 'S'
        WHEN AVG(SCORE) >= 90  THEN 'A'
        WHEN AVG(SCORE) >= 80  THEN 'B'
        ELSE 'C' END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO)

SELECT 
    H.EMP_NO,
    H.EMP_NAME,
    E.GRADE,
    CASE WHEN E.GRADE = 'S' THEN SAL * 20/100
    WHEN E.GRADE = 'A' THEN SAL * 15/100
    WHEN E.GRADE = 'B' THEN SAL * 10/100
    ELSE 0 END AS BONUS
FROM HR_EMPLOYEES H
JOIN EMP_SCORE E
ON H.EMP_NO = E.EMP_NO
ORDER BY H.EMP_NO
*/