/*
SELECT
    HOUR(DATETIME) AS 'HOUR',
    COUNT(ANIMAL_ID) AS 'COUNT'
FROM
    ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20
GROUP BY HOUR(DATETIME)
ORDER BY HOUR; */

SELECT 
    HOUR(DATETIME) AS 'HOUR',
    COUNT(ANIMAL_ID) AS 'COUNT'
FROM 
    ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR >= 9 AND HOUR < 20
ORDER BY HOUR;