-- 코드를 입력하세요
WITH SUB AS (
        SELECT MEMBER_ID, 
                COUNT(MEMBER_ID)
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(MEMBER_ID) DESC
        LIMIT 1
)

SELECT
    P.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R USING (MEMBER_ID)
WHERE P.MEMBER_ID = (
                SELECT MEMBER_ID
                FROM SUB

            )
ORDER BY REVIEW_DATE, REVIEW_TEXT