-- 코드를 작성해주세요
SELECT
    D.ID,
    D.GENOTYPE,
    P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA D
INNER JOIN ECOLI_DATA P
ON D.PARENT_ID = P.ID
WHERE P.GENOTYPE & D.GENOTYPE = P.GENOTYPE
ORDER BY D.ID;