-- 코드를 작성해주세요

SELECT 
    ID,
    FISH_NAME,
    LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
USING (FISH_TYPE)
WHERE (I.FISH_TYPE, I.LENGTH) IN (
                    SELECT FISH_TYPE, MAX(LENGTH)
                    FROM FISH_INFO
                    GROUP BY FISH_TYPE

)
ORDER BY ID;