-- 코드를 작성해주세요
SELECT 
    SUM(G.SCORE) AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES E
INNER JOIN HR_GRADE G
USING (EMP_NO)
INNER JOIN HR_DEPARTMENT D 
USING (DEPT_ID)
GROUP BY EMP_NO
ORDER BY SCORE DESC LIMIT 1