SELECT
    CONCAT('/home/grep/src/', B.BOARD_ID , '/' , F.FILE_ID , F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_FILE F
USING (BOARD_ID)
WHERE VIEWS = (SELECT MAX(VIEWS)
              FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;




/*

TODAYS 
CONCAT(문자열 합치기) , DATEDIFF(날짜 차이 계산)
*/