WITH FRONT_END AS (
    SELECT SUM(CODE) AS SCORE
    FROM SKILLCODES
    WHERE 1=1
    AND CATEGORY = 'Front End'
) 
SELECT CASE 
    WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') 
    AND D.SKILL_CODE & (SELECT SCORE FROM FRONT_END)
    THEN 'A'
    WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
    THEN 'B'
    WHEN D.SKILL_CODE & (SELECT SCORE FROM FRONT_END)
    THEN 'C'
    END AS GRADE
    , D.ID
    , D.EMAIL
FROM DEVELOPERS D
HAVING GRADE IS NOT NULL
ORDER BY GRADE, D.ID